version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: note
    binary: note
    main: ./main.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/nathan-nicholson/note/internal/version.Version={{.Version}}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
# brews:
#   - name: note
#     repository:
#       owner: nathan-nicholson
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

#     # Git author used to commit to the repository
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com

#     # Your app's homepage
#     homepage: "https://github.com/nathan-nicholson/note"

#     # Your app's description
#     description: "A lightweight CLI tool for capturing quick notes and managing todos with project-based organization"

#     # License
#     license: "MIT"

#     # Setting this will prevent goreleaser to actually try to commit the updated
#     # formula - useful for testing
#     skip_upload: false

#     # Directory inside the repository to put the formula
#     directory: Formula

#     # Dependencies
#     dependencies:
#       - name: sqlite

#     # Install script
#     install: |
#       bin.install "note"

#     # Test script
#     test: |
#       system "#{bin}/note", "--help"
